databases:
  - name: project0db
    plan: free
    databaseName: project0
    user: project0user

services:
  - type: web
    plan: free
    name: project0
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project0db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4